version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: engineer_status_development
      POSTGRES_USER: engineer_status
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/engineer_status
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://engineer_status:password@db:5432/engineer_status_development

  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash -c "yarn install && yarn start"
    ports:
      - "3002:3000"
    depends_on:
      - web

volumes:
  postgres-data:
