name: RuboCop

on:
  pull_request:
    branches:  # すべてのブランチに対応
      - '**'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3
          bundler-cache: true

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install 

      - name: Run rubocop # Rubocopを実行します。
        run: bundle exec rubocop
